from setuptools import setup, find_packages

setup(
	name='shoreline_transects',
	version='1.0',
	author='Henri De Boever',
	author_email='henrideboever@gmail.com',
	url='cascadiacoast.com',
	license='MIT',
	description='A tool to generate perpendicular transects given an input list of reaches that define an area of interest.',
	classifiers=[
		'Development Status :: 4 - Beta',
		'Environment :: Console',
		'Intended Audience :: Developers',
		'Intended Audience :: Science/Research',
		'License :: OSI Approved :: MIT License',
		'Natural Language :: English',
		'Operating System :: MacOS :: MacOS X',
		'Operating System :: Microsoft :: Windows',
		'Operating System :: POSIX',
		'Operating System :: Unix',
		'Programming Language :: Python :: 2.7',
		'Programming Language :: Python :: 3',
		'Programming Language :: Python :: 3.2',
		'Programming Language :: Python :: 3.3',
		'Programming Language :: Python :: 3.4',
		'Programming Language :: Python :: 3.5',
		'Programming Language :: Python :: 3.6',
		'Programming Language :: Python :: 3.7',
		'Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator',
	],
	keywords=['Shoreline Transect Generator'],
	packages=find_packages(exclude=['docs', 'data', 'notebooks', 'tests', 'cover']),
	python_requires='>=2.7, <4',
	install_requires=[
		'matplotlib',
		'numpy',
		'scipy',
		'mpl_toolkits.basemap',
		'simplekml',
		'pyproj',
		'shapely',
	],
)
